apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-cloud-manager-front
  name: kube-cloud-manager-front
  namespace: kube-cloud-manager
spec:

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: kube-cloud-manager-front