apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: kube-cloud-manager
spec:
  type: NodePort
  ports:
    - name: http
      port: 3306
      targetPort: http
      protocol: TCP
  selector:
    app: mysql